# Need to point to the correct paths
train_path: training_dataset/raw_datasets/1000
benchmark_path: test_set

### Test (Not influence the training)
model_path: run/False/2022-11-07/13-46-03/Exp_weights/1000000_log_-epoch=104-val_loss=0.00.ckpt
### 

num_of_workers: 6
batch_size: 50 # 50 ideal if gpu(rtx 3080) is empty 
precision: 16
accelerator: "gpu" # Use gpu 
accelerator_devices: 1 # Number of the gpu to use
resume_from_checkpoint: ""

path_to_candidate: configs/equations_ops_3_5000.json # This is the file that contains the negative equations from which the model will sample the absent branches 